<div style="float: left; padding-right: 16px;">
<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
</div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserIdentity()->getFirstname().' '.$this->zfcUserIdentity()->getLastname(); ?></h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Logout'); ?>]</a>
<div style="clear: both;"></div>
