<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<div class="content-section-a login-content">
	<div class="row">
		<div class="header-login col-lg-4 col-md-4 col-sm-12 col-md-offset-4">
            <h1>Register Here:</h1>
            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
            <?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>
			<div>
				<?php echo $this->form()->openTag($form) ?>
                
                <?php foreach ($form as $element): ?>
                <p class="form-row">
                    <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                        <?php //echo $this->formLabel($element) ?>
                    <?php endif ?>
                    <?php if ($element instanceof Zend\Form\Element\Button): ?>
                        <?php echo $this->formButton($element) ?>
                    <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                        <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
                    <?php else: ?>
                        <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
                    <?php endif ?>
                </p>
                <?php endforeach ?>
                
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>
            <?php echo $this->form()->closeTag() ?>
			</div>
		</div>
	</div>
</div>
